name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # use the same version as your project

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      # Uncomment if you want static export (only if using `next export`)
      # - name: Export static site
      #   run: npm run export

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for PR integration
          action: "upload"
          app_location: "/"
          api_location: ""   # leave empty if not using a backend API
          output_location: ".next" # change to "out" if using next export
